- name: Install Nginx and Certbot
  package:
    name:
      - nginx
      - certbot
      - python3-certbot-nginx
    state: present

- name: Install Nginx config
  copy:
    src: ./etc
    dest: /

- name: Remove /etc/nginx/sites-enabled/default
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Create /srv/certbot
  file:
    path: /srv/certbot
    state: directory

- name: Run certbot
  command: /usr/bin/certbot -n --agree-tos --rsa-key-size 4096 --nginx -d media.smallest.dog -m me@duckie.co --webroot --webroot-path /srv/certbot
  args:
    creates: /etc/letsencrypt/live/media.smallest.dog/fullchain.pem

- name: Add Certbot cron job
  cron:
    name: "run certbot"
    hour: 12
    job: "/usr/bin/certbot renew --rsa-key-size 4096 --webroot --webroot-path /srv/certbot --quiet"

- name: Enable and start Nginx service
  systemd:
    name: nginx
    enabled: yes
    state: started
