- name: Add Jellyfin team GPG keys
  ansible.builtin.apt_key:
    url: https://repo.jellyfin.org/jellyfin_team.gpg.key

- name: Add Jellyfin apt repo
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://repo.jellyfin.org/ubuntu focal main
    filename: jellyfin
    state: present

- name: Install Jellyfin
  ansible.builtin.apt:
    update_cache: true
    name: jellyfin
    state: present

- name: Install libnss3-tools (for certutil)
  ansible.builtin.apt:
    name: jellyfin
    state: present

#- name: Add Jellyfin user
#  user:
#    name: jellyfin

- name: Install Jellyfin configs
  synchronize:
    src: etc/
    dest: /etc/
