- name: Install required python modules for Ansible
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-compose

- name: Add Jellyfin user
  user:
    name: jellyfin

- name: Install Jellyfin/Nginx config
  synchronize:
    src: etc/
    dest: /etc/

- name: Install Jellyfin config and scripts
  synchronize:
    src: jellyfin/
    dest: /usr/local/jellyfin/

- name: Create jellyfin directories
  file:
    path: "{{ item }}"
    owner: jellyfin
    state: directory
  with:
    - /mnt/jellyfin_data/config
    - /mnt/jellyfin_data/cache
    - /mnt/jellyfin_data/media
