# Based on https://infosec.mozilla.org/guidelines/openssh
- name: Set key exchange algos, ciphers, and MAC algos for OpenSSH
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256
      Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
      MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
      # Password based logins are disabled - only public key based logins are allowed.
      AuthenticationMethods publickey

- name: Check sshd config
  command: sshd -t
