- name: Install Docker CE prerequisites
  package:
    name:
      - apt-transport-https
      - ca-certificates
      #- curl # TODO: Remove if not needed.
      - gnupg-agent
      - software-properties-common
      - python3-pip
    state: present

- name: Add Docker CE GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker CE repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install Docker CE
  package:
    name:
      - docker-ce
      - docker-compose
      - containerd.io
    state: present

- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: yes
    state: started
